version: '3'

services:
  traefik:
    image: traefik
    command: --docker.domain=${DOMAIN} --logLevel=${LOG_LEVEL}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme:/acme
      - ./logs:/logs
    networks:
      - traefik-network
    labels:
      - "traefik.backend=traefik"
      - "traefik.enable=true"      
      - "traefik.docker.network=traefik-network"
      - "traefik.port=8080"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:traefik.${PLATFORM}.${DOMAIN}"

  portainer:
    image: portainer/portainer
    restart: unless-stopped
    # ports:
    #  - 9000:9000
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./portainer:/data
    networks:
      - traefik-network
    labels:
      - "traefik.backend=portainer"
      - "traefik.enable=true"      
      - "traefik.docker.network=traefik-network"
      - "traefik.port=9000"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.rule=Host:portainer.${PLATFORM}.${DOMAIN}"

networks:
  traefik-network: